"use client";

import { useMutation } from "convex/react";
import { useState } from "react";
import { api } from "@/convex/_generated/api";
import type { Id } from "@/convex/_generated/dataModel";

type Mission = { _id: Id<"missions">; role: string; lifecycle: string; currentVersion: number; constitution?: string; desiredOutcomes?: string[] };

export function ConstitutionControls({ mission }: Readonly<{ mission: Mission }>) {
  const update = useMutation(api.missions.updateConstitution);
  const [open, setOpen] = useState(false); const [constitution, setConstitution] = useState(mission.constitution ?? ""); const [outcomes, setOutcomes] = useState(mission.desiredOutcomes ?? [""]); const [baseVersion, setBaseVersion] = useState(mission.currentVersion); const [pending, setPending] = useState(false); const [status, setStatus] = useState<string | null>(null); const [key, setKey] = useState<string | null>(null);
  const owner = mission.role === "owner"; const writable = owner && mission.lifecycle === "active";
  function openEditor() { setConstitution(mission.constitution ?? ""); setOutcomes(mission.desiredOutcomes ?? [""]); setBaseVersion(mission.currentVersion); setStatus(null); setOpen(true); }
  async function save() { if (pending) return; if (baseVersion !== mission.currentVersion) { setStatus("Governing intent changed elsewhere. Reopen the editor to review the latest version."); return; } const idempotencyKey = key ?? crypto.randomUUID(); setKey(idempotencyKey); setPending(true); setStatus(null); try { const result = await update({ missionId: mission._id, constitution, desiredOutcomes: outcomes, expectedVersion: baseVersion, idempotencyKey, correlationId: crypto.randomUUID() }); setBaseVersion(result.currentVersion); setStatus("Governing intent saved."); } catch { setKey(null); setStatus("We could not save this Constitution. Check the outcomes and try again."); } finally { setPending(false); } }
  return <section aria-labelledby="constitution-title" className="constitution-controls"><h2 id="constitution-title">Governing intent</h2>{open && writable ? <div><label>Constitution<textarea aria-label="Mission Constitution" disabled={pending} onChange={(event) => setConstitution(event.target.value)} value={constitution} /></label><fieldset disabled={pending}><legend>Desired outcomes (1–20)</legend>{outcomes.map((outcome, index) => <label key={index}>Outcome {index + 1}<input onChange={(event) => setOutcomes((current) => current.map((value, position) => position === index ? event.target.value : value))} value={outcome} />{outcomes.length > 1 ? <button onClick={() => setOutcomes((current) => current.filter((_, position) => position !== index))} type="button">Remove</button> : null}</label>)}<button disabled={outcomes.length >= 20} onClick={() => setOutcomes((current) => [...current, ""])} type="button">Add outcome</button></fieldset><button disabled={pending || baseVersion !== mission.currentVersion} onClick={() => void save()} type="button">{pending ? "Saving…" : "Save governing intent"}</button></div> : <><p>{mission.constitution || "No Constitution has been set yet."}</p><ul>{(mission.desiredOutcomes ?? []).map((outcome) => <li key={outcome}>{outcome}</li>)}</ul>{writable ? <button onClick={openEditor} type="button">Edit governing intent</button> : <p aria-label="Governing intent read-only">{mission.lifecycle === "active" ? "Read-only governing intent." : "Archived Mission — governing intent is read-only."}</p>}</>}{status ? <p aria-live="polite">{status}</p> : null}</section>;
}
